# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your Fedoc title
email: your-email@domain.com
description: site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
permalink: /:categories/:title.html
twitter_username: weishai
github_username:  weishai

# Build settings
markdown: kramdown

# Sass
sass:
  style: compressed
